// Localization Dictionary for English, Odia (ଓଡ଼ିଆ), and Hindi (हिन्दी)

export const TRANSLATIONS = {
  en: {
    selectLanguage: 'Select Language',
    loginTitle: 'Log In / Sign Up',
    enterMobile: 'Enter 10-digit Mobile Number',
    requestOtp: 'Send OTP',
    otpSent: 'OTP has been sent to',
    enterOtp: 'Enter 6-digit OTP Code',
    verifyLogin: 'Verify & Login',
    invalidMobile: 'Please enter a valid 10-digit number.',
    invalidOtp: 'Invalid OTP. Please enter 123456.',
    pickupLoc: 'Pickup Location',
    dropoffLoc: 'Dropoff Location',
    setPickupMap: 'Tap on the map to set pickup location',
    setDropoffMap: 'Tap on the map to set dropoff location',
    selectVehicle: 'What do you need?',
    weightNeed: 'Cargo weight you need to carry',
    bikeDesc: 'Bike - Ideal for documents, food, and small items (< 20 kg)',
    miniTruckDesc: 'Mini Truck (Tata Ace) - Ideal for appliances and light furniture (< 500 kg)',
    largeTruckDesc: 'Large Truck (Tata 407) - Ideal for commercial cargo and relocation (< 2000 kg)',
    bookNow: 'Book Delivery',
    bookingPlaced: 'Booking Placed!',
    findingDriver: 'Finding nearby driver partners...',
    driverAssigned: 'Driver Assigned',
    driverStatus: 'Driver Status',
    otpCode: 'Share OTP with driver on arrival:',
    status_pending: 'Finding driver...',
    status_accepted: 'Driver heading to pickup',
    status_picking_up: 'Driver heading to pickup',
    status_arrived_pickup: 'Driver arrived at pickup',
    status_dropping_off: 'Driver heading to dropoff',
    status_arrived_dropoff: 'Driver arrived at dropoff',
    status_completed: 'Delivered successfully!',
    status_cancelled: 'Booking cancelled',
    cargoWeight: 'Cargo Weight',
    totalPrice: 'Estimated Cost',
    rupeeSymbol: '₹',
    vehicle_bike: 'Bike',
    vehicle_mini_truck: 'Mini Truck (Tata Ace)',
    vehicle_large_truck: 'Large Truck (Tata 407)',
    navigatingToPickup: 'Heading to pickup',
    navigatingToDropoff: 'Heading to dropoff',
    cancelOrder: 'Cancel Booking',
    logout: 'Log Out',
    activeOrder: 'Active Delivery',
    // New keys for redesigned flow
    chooseBikeOrTruck: 'What do you need?',
    bikeOption: 'Two-Wheeler',
    truckOption: 'Truck',
    bikeOptionDesc: 'Small parcels, documents, food',
    truckOptionDesc: 'Furniture, appliances, bulk cargo',
    chooseTruckType: 'Choose truck size',
    truckSuggestion_mini: 'Optimal for 20–500 kg: furniture, appliances',
    truckSuggestion_large: 'Optimal for 500–2000 kg: house shifting, bulk cargo',
    maxCapacity: 'Max capacity',
    searchPickup: 'Search pickup address...',
    searchDropoff: 'Search dropoff address...',
    back: 'Back'
  },
  or: {
    selectLanguage: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
    loginTitle: 'ଲଗ୍ ଇନ୍ / ସାଇନ୍ ଅପ୍',
    enterMobile: '୧୦-ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
    requestOtp: 'OTP ପଠାନ୍ତୁ',
    otpSent: 'OTP ଏହି ନମ୍ବରକୁ ପଠାଯାଇଛି',
    enterOtp: '୬-ଅଙ୍କ ବିଶିଷ୍ଟ OTP କୋଡ୍ ଦିଅନ୍ତୁ',
    verifyLogin: 'ଯାଞ୍ଚ କରି ଲଗ୍ ଇନ୍ କରନ୍ତୁ',
    invalidMobile: 'ଦୟାକରି ଏକ ସଠିକ୍ ୧୦-ଅଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ ।',
    invalidOtp: 'ଭୁଲ୍ OTP । ଦୟାକରି 123456 ଦିଅନ୍ତୁ ।',
    pickupLoc: 'ଉତ୍ସ ସ୍ଥାନ (କେଉଠାରୁ)',
    dropoffLoc: 'ଗନ୍ତବ୍ୟ ସ୍ଥାନ (କେଉଠାକୁ)',
    setPickupMap: 'ଉତ୍ସ ସ୍ଥାନ ସେଟ୍ କରିବାକୁ ମ୍ୟାପ୍‌ରେ ଏକ ସ୍ଥାନ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ',
    setDropoffMap: 'ଗନ୍ତବ୍ୟ ସ୍ଥାନ ସେଟ୍ କରିବାକୁ ମ୍ୟାପ୍‌ରେ ଏକ ସ୍ଥାନ ଉପରେ କ୍ଲିକ୍ କରନ୍ତୁ',
    selectVehicle: 'ଗାଡ଼ିର ପ୍ରକାର ଚୟନ କରନ୍ତୁ',
    weightNeed: 'ପରିବହନ କରିବାକୁ ଥିବା ସାମଗ୍ରୀର ଓଜନ',
    bikeDesc: 'ବାଇକ୍ - ଦସ୍ତାବିଜ୍, ଖାଦ୍ୟ ଏବଂ ଛୋଟ ଜିନିଷ ପାଇଁ ଉପଯୁକ୍ତ (< ୨୦ କିଲୋଗ୍ରାମ)',
    miniTruckDesc: 'ମିନି ଟ୍ରକ୍ (ଟାଟା ଏସି) - ଘରୋଇ ଉପକରଣ ଏବଂ ହାଲୁକା ଆସବାବପତ୍ର ପାଇଁ (< ୫୦୦ କିଲୋଗ୍ରାମ)',
    largeTruckDesc: 'ବଡ଼ ଟ୍ରକ୍ (ଟାଟା ୪୦୭) - ବ୍ୟବସାୟିକ ସାମଗ୍ରୀ ଏବଂ ସ୍ଥାନାନ୍ତର ପାଇଁ (< ୨୦୦୦ କିଲୋଗ୍ରାମ)',
    bookNow: 'ବୁକିଂ କରନ୍ତୁ',
    bookingPlaced: 'ବୁକିଂ ସଫଳ ହେଲା!',
    findingDriver: 'ନିକଟସ୍ଥ ଡ୍ରାଇଭର ଖୋଜା ଚାଲିଛି...',
    driverAssigned: 'ଡ୍ରାଇଭର ନିଯୁକ୍ତ ହେଲେ',
    driverStatus: 'ଡ୍ରାଇଭରଙ୍କ ସ୍ଥିତି',
    otpCode: 'ପହଞ୍ଚିବା ପରେ ଡ୍ରାଇଭରଙ୍କୁ ଏହି OTP କୋଡ୍ ଦିଅନ୍ତୁ:',
    status_pending: 'ଡ୍ରାଇଭର ଖୋଜା ଚାଲିଛି...',
    status_accepted: 'ଡ୍ରାଇଭର ଉତ୍ସ ସ୍ଥାନ ଆଡକୁ ଯାଉଛନ୍ତି',
    status_picking_up: 'ଡ୍ରାଇଭର ଉତ୍ସ ସ୍ଥାନ ଆଡକୁ ଯାଉଛନ୍ତି',
    status_arrived_pickup: 'ଡ୍ରାଇଭର ଉତ୍ସ ସ୍ଥାନରେ ପହଞ୍ଚିଛନ୍ତି',
    status_dropping_off: 'ଡ୍ରାଇଭର ଗନ୍ତବ୍ୟ ସ୍ଥାନ ଆଡକୁ ଯାଉଛନ୍ତି',
    status_arrived_dropoff: 'ଡ୍ରାଇଭର ଗନ୍ତବ୍ୟ ସ୍ଥାନରେ ପହଞ୍ଚିଛନ୍ତି',
    status_completed: 'ସଫଳତାର ସହ ପ୍ରଦାନ କରାଗଲା!',
    status_cancelled: 'ବୁକିଂ ବାତିଲ୍ ହୋଇଛି',
    cargoWeight: 'ସାମଗ୍ରୀର ଓଜନ',
    totalPrice: 'ଆନୁମାନିକ ଭଡ଼ା',
    rupeeSymbol: 'ଟଙ୍କା',
    vehicle_bike: 'ବାଇକ୍',
    vehicle_mini_truck: 'ମିନି ଟ୍ରକ୍ (ଟାଟା ଏସି)',
    vehicle_large_truck: 'ବଡ଼ ଟ୍ରକ୍ (ଟାଟା ୪୦୭)',
    navigatingToPickup: 'ଉତ୍ସ ସ୍ଥାନକୁ ଯାଉଛନ୍ତି',
    navigatingToDropoff: 'ଗନ୍ତବ୍ୟ ସ୍ଥାନକୁ ଯାଉଛନ୍ତି',
    cancelOrder: 'ବୁକିଂ ବାତିଲ୍ କରନ୍ତୁ',
    logout: 'ଲଗ୍ ଆଉଟ୍',
    activeOrder: 'ସକ୍ରିୟ ପରିବହନ',
    chooseBikeOrTruck: 'ଆପଣଙ୍କୁ କ\'ଣ ଦରକାର?',
    bikeOption: 'ଦୁଇ ଚକିଆ',
    truckOption: 'ଟ୍ରକ୍',
    bikeOptionDesc: 'ଛୋଟ ପାର୍ସେଲ, ଦସ୍ତାବିଜ୍, ଖାଦ୍ୟ',
    truckOptionDesc: 'ଆସବାବପତ୍ର, ଉପକରଣ, ଭାରୀ ସାମଗ୍ରୀ',
    chooseTruckType: 'ଟ୍ରକ୍ ର ଆକାର ବାଛନ୍ତୁ',
    truckSuggestion_mini: '୨୦–୫୦୦ କିଗ୍ରା ପାଇଁ ଉପଯୁକ୍ତ: ଆସବାବପତ୍ର, ଉପକରଣ',
    truckSuggestion_large: '୫୦୦–୨୦୦୦ କିଗ୍ରା ପାଇଁ ଉପଯୁକ୍ତ: ଘର ବଦଳ, ଭାରୀ ସାମଗ୍ରୀ',
    maxCapacity: 'ସର୍ବାଧିକ ଧାରଣ ଶକ୍ତି',
    searchPickup: 'ଉତ୍ସ ଠିକଣା ଖୋଜନ୍ତୁ...',
    searchDropoff: 'ଗନ୍ତବ୍ୟ ଠିକଣା ଖୋଜନ୍ତୁ...',
    back: 'ପଛକୁ ଫେରନ୍ତୁ'
  },
  hi: {
    selectLanguage: 'भाषा चुनें',
    loginTitle: 'लॉग इन / साइन अप',
    enterMobile: '10-अंकीय मोबाइल नंबर दर्ज करें',
    requestOtp: 'ओटीपी भेजें',
    otpSent: 'ओटीपी इस नंबर पर भेजा गया है',
    enterOtp: '6-अंकीय ओटीपी कोड दर्ज करें',
    verifyLogin: 'ओटीपी सत्यापित करें',
    invalidMobile: 'कृपया एक सही 10-अंकीय मोबाइल नंबर दर्ज करें।',
    invalidOtp: 'अमान्य ओटीपी। कृपया 123456 दर्ज करें।',
    pickupLoc: 'पिकअप स्थान (कहाँ से)',
    dropoffLoc: 'ड्रॉप स्थान (कहाँ तक)',
    setPickupMap: 'पिकअप स्थान सेट करने के लिए मानचित्र पर किसी स्थान पर क्लिक करें',
    setDropoffMap: 'ड्रॉप स्थान सेट करने के लिए मानचित्र पर किसी स्थान पर क्लिक करें',
    selectVehicle: 'वाहन का प्रकार चुनें',
    weightNeed: 'ले जाने वाले सामान का वजन',
    bikeDesc: 'बाइक - दस्तावेजों, भोजन और छोटे सामानों के लिए आदर्श (< 20 किलोग्राम)',
    miniTruckDesc: 'मिनी ट्रक (टाटा एस) - घरेलू उपकरणों और हल्के फर्नीचर के लिए आदर्श (< 500 किलोग्राम)',
    largeTruckDesc: 'बड़ा ट्रक (टाटा 407) - व्यावसायिक कार्गो और स्थानांतरण के लिए आदर्श (< 2000 किलोग्राम)',
    bookNow: 'डिलीवरी बुक करें',
    bookingPlaced: 'बुकिंग सफल रही!',
    findingDriver: 'निकटतम ड्राइवर की तलाश की जा रही है...',
    driverAssigned: 'ड्राइवर असाइन किया गया',
    driverStatus: 'ड्राइवर की स्थिति',
    otpCode: 'आगमन पर ड्राइवर के साथ ओटीपी कोड साझा करें:',
    status_pending: 'ड्राइवर की तलाश की जा रही है...',
    status_accepted: 'ड्राइवर पिकअप के लिए आ रहा है',
    status_picking_up: 'ड्राइवर पिकअप के लिए आ रहा है',
    status_arrived_pickup: 'ड्राइवर पिकअप पर पहुंच गया है',
    status_dropping_off: 'ड्राइवर ड्रॉप स्थान के लिए रवाना है',
    status_arrived_dropoff: 'ड्राइवर ड्रॉप स्थान पर पहुंच गया है',
    status_completed: 'सफलतापूर्वक डिलीवर किया गया!',
    status_cancelled: 'बुकिंग रद्द कर दी गई',
    cargoWeight: 'सामान का वजन',
    totalPrice: 'अनुमानित किराया',
    rupeeSymbol: '₹',
    vehicle_bike: 'बाइक',
    vehicle_mini_truck: 'मिनी ट्रक (टाटा एस)',
    vehicle_large_truck: 'बड़ा ट्रक (टाटा 407)',
    navigatingToPickup: 'पिकअप की ओर बढ़ रहे हैं',
    navigatingToDropoff: 'ड्रॉप की ओर बढ़ रहे हैं',
    cancelOrder: 'बुकिंग रद्द करें',
    logout: 'लॉग आउट',
    activeOrder: 'सक्रिय डिलीवरी',
    chooseBikeOrTruck: 'आपको क्या चाहिए?',
    bikeOption: 'दो-पहिया',
    truckOption: 'ट्रक',
    bikeOptionDesc: 'छोटे पार्सल, दस्तावेज, भोजन',
    truckOptionDesc: 'फर्नीचर, उपकरण, भारी सामान',
    chooseTruckType: 'ट्रक का आकार चुनें',
    truckSuggestion_mini: '20–500 किग्रा के लिए उपयुक्त: फर्नीचर, उपकरण',
    truckSuggestion_large: '500–2000 किग्रा के लिए उपयुक्त: घर शिफ्टिंग, भारी माल',
    maxCapacity: 'अधिकतम क्षमता',
    searchPickup: 'पिकअप पता खोजें...',
    searchDropoff: 'ड्रॉप पता खोजें...',
    back: 'वापस जाएँ'
  }
};
